### ISSUE TITLE
Hello, do you have any plans to open source code in the near future?

### ISSUE THREAD

**Issue by ghost** [yuxuan1206/NF-Atlas#2]
Hello, do you have any plans to open source code in the near future?

**Comment by ghost** [comment]
您好，请问会在不久后开源吗？

**Comment by tripathiarpan20** [comment]
Same question

**Comment by yuxuan1206** [comment]
I'm sorry for the open source delay because of some cooperation approval problems. It was recently approved, and we'll be open sourcing it in two weeks. Thanks for your attention.
